# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marco-xxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marco
  template:
    metadata:
      labels:
        app: marco
    spec:
      containers:
      - name: marco-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/machinelearning-xxxx/marco-xxx:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
